language: scala

scala:
  - 2.11.6

jdk:
  - oraclejdk8

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3284e9e836eeccd3754a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false